INSERT INTO vhs (vhs_id, title) VALUES (1, 'Back to the future 1');
INSERT INTO vhs (vhs_id, title) VALUES (2, 'Back to the future 2');
INSERT INTO vhs (vhs_id, title) VALUES (3, 'Back to the future 3');
INSERT INTO vhs (vhs_id, title) VALUES (4, 'Lord of the Rings: The Fellowship of the Ring');
INSERT INTO vhs (vhs_id, title) VALUES (5, 'Lord of the Rings: The Two Towers');
INSERT INTO vhs (vhs_id, title) VALUES (7, 'Star Wars Episode 1: A New Hope');
INSERT INTO vhs (vhs_id, title) VALUES (8, 'Star Wars Episode 2: Attack of The Clones');
INSERT INTO vhs (vhs_id, title) VALUES (9, 'Star Wars Episode 3: Revenge Of The Sith');
INSERT INTO vhs (vhs_id, title) VALUES (10, 'Star Wars Episode 4: A New Hope');
INSERT INTO vhs (vhs_id, title) VALUES (11, 'Star Wars Episode 5: Empire Strikes Back');
INSERT INTO vhs (vhs_id, title) VALUES (12, 'Star Wars Episode 6: The Return of the Jedi');
INSERT INTO vhs (vhs_id, title) VALUES (13, 'Star Wars Episode 7: Force Awakens');
INSERT INTO vhs (vhs_id, title) VALUES (14, 'Star Wars Episode 8: The Last Jedi');
INSERT INTO vhs (vhs_id, title) VALUES (15, 'Star Wars Episode 9: The Rise of Skywalker');
INSERT INTO vhs (vhs_id, title) VALUES (16, 'Harry Potter and The Sorcerers Stone');
INSERT INTO vhs (vhs_id, title) VALUES (17, 'Harry Potter and The Chamber of Secrets');
INSERT INTO vhs (vhs_id, title) VALUES (18, 'Harry Potter and The Prisoner of Azkaban');
INSERT INTO vhs (vhs_id, title) VALUES (19, 'Harry Potter and The Goblet of Fire');
INSERT INTO vhs (vhs_id, title) VALUES (20, 'Harry Potter and The Order of the Phoenix');
INSERT INTO vhs (vhs_id, title) VALUES (21, 'Harry Potter and The Half-Blood Prince');
INSERT INTO vhs (vhs_id, title) VALUES (22, 'Harry Potter and The Deathly Hallows');
INSERT INTO vhs (vhs_id, title) VALUES (23, 'Reservoir Dogs');
INSERT INTO vhs (vhs_id, title) VALUES (24, 'Pulp Fiction');
INSERT INTO vhs (vhs_id, title) VALUES (25, 'Kill Bill vol. 1');
INSERT INTO vhs (vhs_id, title) VALUES (26, 'Kill Bill vol. 2');
INSERT INTO vhs (vhs_id, title) VALUES (27, 'Inglorious Bastards');
INSERT INTO vhs (vhs_id, title) VALUES (28, 'Django Unchained');
INSERT INTO vhs (vhs_id, title) VALUES (29, 'The Hateful Eight');
INSERT INTO vhs (vhs_id, title) VALUES (30, 'Once upon a time... in Hollywood');
INSERT INTO vhs (vhs_id, title) VALUES (31, 'The Shawshank Redemption');

INSERT INTO korisnik (user_id, active, password, role, username) VALUES (1, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_ADMIN', 'mamba');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (2, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_ADMIN', 'dirk');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (3, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'lukadoncic');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (4, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'lebronjames');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (5, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'devinbooker');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (6, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'giannis');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (7, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'kevindurant');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (8, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'stephcurry');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (9, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'traeyoung');
INSERT INTO korisnik (user_id, active, password, role, username) VALUES (10, TRUE, '$2a$10$9fIidnC6qS0V87BcUlcGx.0s7Uv6S3zaBwn5f6UF74t1h1y1L256G', 'ROLE_USER', 'nikolajokic');

INSERT INTO rental (rental_id, date_from, date_until, user_id, vhs_id, expired) VALUES (1, '2021-06-25 12:00:00', '2021-07-04 12:00:00', 4, 24, FALSE);
INSERT INTO rental (rental_id, date_from, date_until, user_id, vhs_id, expired) VALUES (2, '2021-06-23 12:00:00', '2021-07-02 12:00:00', 4, 29, FALSE);
INSERT INTO rental (rental_id, date_from, date_until, user_id, vhs_id, expired) VALUES (3, '2021-06-24 12:00:00', '2021-07-10 12:00:00', 6, 15, FALSE);
INSERT INTO rental (rental_id, date_from, date_until, user_id, vhs_id, expired) VALUES (4, '2021-06-21 12:00:00', '2021-07-01 12:00:00', 8, 5, FALSE);